### ISSUE TITLE
vue-simple-icons name is claimed

### ISSUE THREAD

**Issue by sh7dm** [sh7dm/vue-simpleicons#22]
There already is the [vue-simple-icons package](https://www.npmjs.com/package/vue-simple-icons) in npm! @gabrieledarrigo @ericcornelissen What should we do?

**Comment by sh7dm** [comment]
@ericcornelissen ok, or maybe rename the package?

**Comment by ericcornelissen** [comment]
If all else fails we can have a look at that, but "vue-simple-icons" is a perfect name for this project and the other project looks to be abandoned anyway.

**Comment by sh7dm** [comment]
@ericcornelissen I wrote a message on [the website](http://romina.io/)

**Comment by ericcornelissen** [comment]
That is unfortunate, I've contacted the package owner on Twitter, if I don't get a response soon I will contact npm support to see if they have a solution.

**Comment by ericcornelissen** [comment]
Neither was successful, I suggest rebranding to [vue-simpleicons](https://www.npmjs.com/search?q=vue-simpleicons). Although it might be a little bit confusing, I think it's the best we can do...

**Comment by sh7dm** [comment]
@ericcornelissen okay, have you contacted NPM?
